all
htmlacademy-htmlcss/1593103-device-29 pull request #5
Opened 2020-10-26 02:21 UTC by bsgribtmfu

2020-10-26 20:18 UTC, Shramkoweb requested changes

2020-10-26 20:18 UTC, Shramkoweb commented on catalog.html
> +                <button href="#"></button>
href="#" у кнопок?)

2020-10-26 20:18 UTC, Shramkoweb commented on catalog.html
> +                <button href="#"></button>
И чего они пустые?

2020-10-26 20:18 UTC, Shramkoweb commented on catalog.html
> +            <h2 class="visually-hidden"> Список моноподов для селфи</h2>
Мне кажется он прям лишний тут - у нас описывающий h1 уже примерно такой же

2020-10-26 20:18 UTC, Shramkoweb commented on catalog.html
> +                    <button href="#" class="button" aria-label="Добавить товар Любительская селфи-палка в корзину">В корзину</button>
То же сслыкой лучше. делай на всякий пожарный =)

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +
Потом перед проверкой их убрать нужно. Пока пускай будут

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +
Я про коментарии =)

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +  width: 1040px;
width: 100%; 
Не ?

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
>    font-family: "Gilroy", "Arial", sans-serif;
У тебя в некоторых местах "Arial", а в других Arial - приведи к одному виду.
У академии есть в криетриях гдето или стайл-гайде

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
>    grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr;
repeat(6, 1fr)

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
>    grid-template-columns: 1fr 1fr 1fr 1fr;
repeat(4, 1fr)

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +.footer-social-list li:not(:last-child) {
Прям нужна такая сложность? Я думаю можно упростить

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +.page-catalog {}
Удалить)

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +.page-catalog h1 {
Класс на заголовок и убирай вложеность

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +  font-family: Gilroy;
Критерий по шрифтам не пройдешь

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +.crumbs-item:not(:last-child) a:hover {
Опять же очень сложно - попробуй упростить

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +.crumbs-item:not(:last-child) a:active {
Сложно

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +.crumbs-item:not(:last-child)::after {
Сложно)

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +  background-image: url(../img/button-sort.svg);
путь в url должен быть в кавычках

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +.catalog-sort-list li:active                  { opacity: 1.0; }
А чего тут другое форматирование вдруг?)

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +.catalog-sort-buttons li:active               { opacity: 1.0; }
1.0 -> 1

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
>    font-family: "Gilroy", Arial, sans-serif;
Шрифт

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +.product-image.new::before {
Просто .new::before  ?

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +  font-family: Gilroy;
Шрифт

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +  font-family: Open Sans;
Шрифт

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
>    font-family: "Gilroy", Arial, sans-serif;
Шрифт

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +  font-family: Gilroy;
Шрифт

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +.range-controls .scale {
Старайся убрать вложеность, там где в ней нет нужды

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +  font-family: Open Sans;
Шрифт

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +  background-image: url(../img/check.svg);
урла в кавычках

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +  font-weight: 800;
А у тебя точно есть такой жирности шрифт?

2020-10-26 20:18 UTC, Shramkoweb commented on css/main.css
> +  background-color: #EAEAEA;
Почему не в переменных?

2020-10-26 20:22 UTC, bsgribtmfu commented on catalog.html
> +                <button href="#"></button>
раньше они были ссылками :D

2020-10-26 20:35 UTC, bsgribtmfu commented on css/main.css
> +  width: 1040px;
нет, я позиционирую относительно элемента списка:
`.user-navigation li {
  position: relative;
}`

2020-10-27 04:55 UTC, Shramkoweb commented on catalog.html
> +                <button aria-label="Сортировка по возрастанию"><span class="visually-hidden">По возрастанию<</span></button>
У нас уже есть контент который читает скрин ридер. Ариа не нужно

2020-10-27 06:29 UTC, merged